#pragma once
#include "../lib/glad/glad/glad.h"
#include <cglm/affine.h>
#include <cglm/call/affine.h>
#include <cglm/cam.h>
#include <cglm/mat4.h>
#include <cglm/util.h>
#include <cglm/affine-pre.h>
#include <cglm/vec3.h>
#include <stdio.h>
#include <stdbool.h>
#include "camera/camera.h"
#include "object/object.h"
#include "shader/shader.h"
#include <GLFW/glfw3.h>
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"